EXENAME          = v68

MAINFILES        = v68.c ide.c
MUSASHIFILES     = m68kcpu.c m68kdasm.c
MUSASHIGENCFILES = m68kops.c m68kopac.c m68kopdm.c m68kopnz.c
MUSASHIGENHFILES = m68kops.h
MUSASHIGENERATOR = m68kmake

.CFILES   = $(MAINFILES) $(MUSASHIFILES) $(MUSASHIGENCFILES)
.OFILES   = $(.CFILES:%.c=%.o)

CC        = gcc -O2
WARNINGS  = -Wall -pedantic
CFLAGS    = $(WARNINGS)
LFLAGS    = $(WARNINGS)

TARGET = $(EXENAME)

DELETEFILES = $(MUSASHIGENCFILES) $(MUSASHIGENHFILES) $(.OFILES) $(TARGET) $(MUSASHIGENERATOR)

all: $(TARGET)

clean:
	rm -f $(DELETEFILES)

$(TARGET): $(MUSASHIGENHFILES) $(.OFILES) Makefile
	$(CC) -o $@ $(.OFILES) $(LFLAGS)

$(MUSASHIGENCFILES) $(MUSASHIGENHFILES): $(MUSASHIGENERATOR)
	./$(MUSASHIGENERATOR)

$(MUSASHIGENERATOR):  $(MUSASHIGENERATOR).c
	$(CC) -o  $(MUSASHIGENERATOR)  $(MUSASHIGENERATOR).c
