MAINFILES        = v68.c ide.c
MAINFILEST       = tiny68k.c ide.c
MUSASHIFILES     = m68kcpu.c m68kdasm.c
MUSASHIGENCFILES = m68kops.c m68kopac.c m68kopdm.c m68kopnz.c
MUSASHIGENHFILES = m68kops.h
MUSASHIGENERATOR = m68kmake

.CFILES   = $(MAINFILES) $(MUSASHIFILES) $(MUSASHIGENCFILES)
.OFILES   = $(.CFILES:%.c=%.o)

.CFILEST   = $(MAINFILEST) $(MUSASHIFILES) $(MUSASHIGENCFILES)
.OFILEST   = $(.CFILEST:%.c=%.o)

CC        = gcc -O2
WARNINGS  = -Wall -pedantic
CFLAGS    = $(WARNINGS)
LFLAGS    = $(WARNINGS)

TAGRET	  = v68 tiny68k

DELETEFILES = $(MUSASHIGENCFILES) $(MUSASHIGENHFILES) $(.OFILES) $(.OFILEST) $(TARGET) $(MUSASHIGENERATOR) *~

all: v68 tiny68k

clean:
	rm -f $(DELETEFILES)

v68: $(MUSASHIGENHFILES) $(.OFILES) Makefile
	$(CC) -o $@ $(.OFILES) $(LFLAGS)

tiny68k: $(MUSASHIGENHFILES) $(.OFILEST) Makefile
	$(CC) -o $@ $(.OFILEST) $(LFLAGS)

$(MUSASHIGENCFILES) $(MUSASHIGENHFILES): $(MUSASHIGENERATOR)
	./$(MUSASHIGENERATOR)

$(MUSASHIGENERATOR):  $(MUSASHIGENERATOR).c
	$(CC) -o  $(MUSASHIGENERATOR)  $(MUSASHIGENERATOR).c
